// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class Book
        {
            private static FormLink<IBookGetter> Construct(uint id) => new FormLink<IBookGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IBookGetter> KYE_book_furred => Construct(0x6fe99);
            public static FormLink<IBookGetter> KYE_book_fat => Construct(0x7a0a1);
            public static FormLink<IBookGetter> KYE_book_big => Construct(0x7f1a6);
            public static FormLink<IBookGetter> KYE_book_small => Construct(0x842ab);
            public static FormLink<IBookGetter> KYE_book_armored => Construct(0x893b0);
            public static FormLink<IBookGetter> KYE_book_dwarven_machine => Construct(0x8e4b4);
            public static FormLink<IBookGetter> KYE_book_undead => Construct(0x935b9);
            public static FormLink<IBookGetter> KYE_book_venomous => Construct(0x986be);
            public static FormLink<IBookGetter> KYE_book_elemental => Construct(0x9d7c2);
            public static FormLink<IBookGetter> KYE_book_plant => Construct(0xa79d9);
            public static FormLink<IBookGetter> KYE_book_vile => Construct(0xa79db);
            public static FormLink<IBookGetter> KYE_book_skeletal => Construct(0xa79dc);
            public static FormLink<IBookGetter> KYE_book_trollkin => Construct(0xa79dd);
            public static FormLink<IBookGetter> KYE_book_weak_willed => Construct(0xa79de);
            public static FormLink<IBookGetter> KYE_book_strong_willed => Construct(0xa79df);
            public static FormLink<IBookGetter> KYE_book_cave_dwelling => Construct(0xa79e0);
            public static FormLink<IBookGetter> KYE_book_vascular => Construct(0xa79e1);
            public static FormLink<IBookGetter> KYE_book_aquatic => Construct(0xa79e2);
            public static FormLink<IBookGetter> KYE_book_brittle => Construct(0xa79e3);
            public static FormLink<IBookGetter> KYE_book_supernatural => Construct(0xa79e4);
            public static FormLink<IBookGetter> KYE_book_rocky => Construct(0xa79e5);
            public static FormLink<IBookGetter> kye_know_your_armor => Construct(0xb6d02);
        }
    }
}
