// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class Book
        {
            private static FormLink<IBookGetter> Construct(uint id) => new FormLink<IBookGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IBookGetter> KYE_book_furred => Construct(0x849);
            public static FormLink<IBookGetter> KYE_book_fat => Construct(0x84c);
            public static FormLink<IBookGetter> KYE_book_big => Construct(0x84e);
            public static FormLink<IBookGetter> KYE_book_small => Construct(0x850);
            public static FormLink<IBookGetter> KYE_book_armored => Construct(0x852);
            public static FormLink<IBookGetter> KYE_book_dwarven_machine => Construct(0x854);
            public static FormLink<IBookGetter> KYE_book_undead => Construct(0x856);
            public static FormLink<IBookGetter> KYE_book_venomous => Construct(0x858);
            public static FormLink<IBookGetter> KYE_book_elemental => Construct(0x85a);
            public static FormLink<IBookGetter> KYE_book_plant => Construct(0x867);
            public static FormLink<IBookGetter> KYE_book_vile => Construct(0x869);
            public static FormLink<IBookGetter> KYE_book_skeletal => Construct(0x86a);
            public static FormLink<IBookGetter> KYE_book_trollkin => Construct(0x86b);
            public static FormLink<IBookGetter> KYE_book_weak_willed => Construct(0x86c);
            public static FormLink<IBookGetter> KYE_book_strong_willed => Construct(0x86d);
            public static FormLink<IBookGetter> KYE_book_cave_dwelling => Construct(0x86e);
            public static FormLink<IBookGetter> KYE_book_vascular => Construct(0x86f);
            public static FormLink<IBookGetter> KYE_book_aquatic => Construct(0x870);
            public static FormLink<IBookGetter> KYE_book_brittle => Construct(0x871);
            public static FormLink<IBookGetter> KYE_book_supernatural => Construct(0x872);
            public static FormLink<IBookGetter> KYE_book_rocky => Construct(0x873);
            public static FormLink<IBookGetter> kye_know_your_armor => Construct(0x87b);
        }
    }
}
