// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class Keyword
        {
            private static FormLink<IKeywordGetter> Construct(uint id) => new FormLink<IKeywordGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IKeywordGetter> kye_armor_full => Construct(0xb6d03);
            public static FormLink<IKeywordGetter> kye_armor_warm => Construct(0xb6d04);
            public static FormLink<IKeywordGetter> kye_armor_leathery => Construct(0xb6d05);
            public static FormLink<IKeywordGetter> kye_armor_brittle => Construct(0xb6d06);
            public static FormLink<IKeywordGetter> kye_armor_nonconductive => Construct(0xb6d07);
            public static FormLink<IKeywordGetter> kye_armor_thick => Construct(0xb6d08);
            public static FormLink<IKeywordGetter> kye_armor_metal => Construct(0xb6d09);
            public static FormLink<IKeywordGetter> kye_armor_layered => Construct(0xb6d0a);
            public static FormLink<IKeywordGetter> kye_armor_deep => Construct(0xb6d0b);
        }
    }
}
