// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class LeveledItem
        {
            private static FormLink<ILeveledItemGetter> Construct(uint id) => new FormLink<ILeveledItemGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILeveledItemGetter> kye_book_basic => Construct(0x874);
            public static FormLink<ILeveledItemGetter> kye_book_advanced => Construct(0x875);
            public static FormLink<ILeveledItemGetter> kye_book_magic => Construct(0x876);
            public static FormLink<ILeveledItemGetter> kye_book_any => Construct(0x877);
            public static FormLink<ILeveledItemGetter> kye_book_any_physical_bias => Construct(0x878);
            public static FormLink<ILeveledItemGetter> kye_book_any_magic_bias => Construct(0x879);
        }
    }
}
