// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class LoadScreen
        {
            private static FormLink<ILoadScreenGetter> Construct(uint id) => new FormLink<ILoadScreenGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILoadScreenGetter> kye_furred => Construct(0x800);
            public static FormLink<ILoadScreenGetter> kye_fat => Construct(0x801);
            public static FormLink<ILoadScreenGetter> kye_big => Construct(0x802);
            public static FormLink<ILoadScreenGetter> kye_small_1 => Construct(0x803);
            public static FormLink<ILoadScreenGetter> kye_small_2 => Construct(0x804);
            public static FormLink<ILoadScreenGetter> kye_armored => Construct(0x805);
            public static FormLink<ILoadScreenGetter> kye_dwarven_machine_2 => Construct(0x806);
            public static FormLink<ILoadScreenGetter> kye_undead_1 => Construct(0x807);
            public static FormLink<ILoadScreenGetter> kye_undead_2 => Construct(0x808);
            public static FormLink<ILoadScreenGetter> kye_venomous => Construct(0x809);
            public static FormLink<ILoadScreenGetter> kye_iceelemental => Construct(0x80a);
            public static FormLink<ILoadScreenGetter> kye_brittle => Construct(0x80b);
            public static FormLink<ILoadScreenGetter> kye_fireelemental => Construct(0x80c);
            public static FormLink<ILoadScreenGetter> kye_shockelemental => Construct(0x80d);
            public static FormLink<ILoadScreenGetter> kye_plant => Construct(0x80e);
            public static FormLink<ILoadScreenGetter> kye_vile => Construct(0x80f);
            public static FormLink<ILoadScreenGetter> kye_skeletal => Construct(0x810);
            public static FormLink<ILoadScreenGetter> kye_trollkin => Construct(0x811);
            public static FormLink<ILoadScreenGetter> kye_weakwilled => Construct(0x812);
            public static FormLink<ILoadScreenGetter> kye_weakwilled_2 => Construct(0x813);
            public static FormLink<ILoadScreenGetter> kye_strongwilled => Construct(0x814);
            public static FormLink<ILoadScreenGetter> kye_cavedwelling_2 => Construct(0x815);
            public static FormLink<ILoadScreenGetter> kye_vascular => Construct(0x816);
            public static FormLink<ILoadScreenGetter> kye_aquatic => Construct(0x817);
            public static FormLink<ILoadScreenGetter> kye_dwarven_machine => Construct(0x837);
        }
    }
}
