// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class MagicEffect
        {
            private static FormLink<IMagicEffectGetter> Construct(uint id) => new FormLink<IMagicEffectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IMagicEffectGetter> kye_mgef_weakness_poison => Construct(0xaa1b);
            public static FormLink<IMagicEffectGetter> kye_mgef_weakness_disease => Construct(0xaa1c);
            public static FormLink<IMagicEffectGetter> kye_mgef_dummy => Construct(0x6ad97);
        }
    }
}
