// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class Perk
        {
            private static FormLink<IPerkGetter> Construct(uint id) => new FormLink<IPerkGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IPerkGetter> kye_perk_fat => Construct(0x82e);
            public static FormLink<IPerkGetter> kye_perk_big => Construct(0x82f);
            public static FormLink<IPerkGetter> kye_perk_small => Construct(0x830);
            public static FormLink<IPerkGetter> kye_perk_armored => Construct(0x831);
            public static FormLink<IPerkGetter> kye_perk_undead => Construct(0x832);
            public static FormLink<IPerkGetter> kye_perk_plant => Construct(0x833);
            public static FormLink<IPerkGetter> kye_perk_skeletal => Construct(0x834);
            public static FormLink<IPerkGetter> kye_perk_brittle => Construct(0x835);
            public static FormLink<IPerkGetter> kye_perk_dwarven_machine => Construct(0x836);
            public static FormLink<IPerkGetter> kye_perk_ghostly => Construct(0x838);
            public static FormLink<IPerkGetter> kye_perk_furred => Construct(0x839);
            public static FormLink<IPerkGetter> kye_perk_supernatural => Construct(0x83a);
            public static FormLink<IPerkGetter> kye_perk_venomous => Construct(0x83b);
            public static FormLink<IPerkGetter> kye_perk_ice_elemental => Construct(0x83c);
            public static FormLink<IPerkGetter> kye_perk_fire_elemental => Construct(0x83d);
            public static FormLink<IPerkGetter> kye_perk_shock_elemental => Construct(0x83e);
            public static FormLink<IPerkGetter> kye_perk_vile => Construct(0x83f);
            public static FormLink<IPerkGetter> kye_perk_troll_kin => Construct(0x840);
            public static FormLink<IPerkGetter> kye_perk_weak_willed => Construct(0x841);
            public static FormLink<IPerkGetter> kye_perk_strong_willed => Construct(0x842);
            public static FormLink<IPerkGetter> kye_perk_cave_dwelling => Construct(0x843);
            public static FormLink<IPerkGetter> kye_perk_vascular => Construct(0x844);
            public static FormLink<IPerkGetter> kye_perk_aquatic => Construct(0x845);
            public static FormLink<IPerkGetter> kye_perk_rocky => Construct(0x846);
            public static FormLink<IPerkGetter> kye_perk_furred_knowledge => Construct(0x84a);
            public static FormLink<IPerkGetter> kye_perk_fat_knowledge => Construct(0x84b);
            public static FormLink<IPerkGetter> kye_perk_big_knowledge => Construct(0x84d);
            public static FormLink<IPerkGetter> kye_perk_small_knowledge => Construct(0x84f);
            public static FormLink<IPerkGetter> kye_perk_armored_knowledge => Construct(0x851);
            public static FormLink<IPerkGetter> kye_perk_dwarven_machine_knowledge => Construct(0x853);
            public static FormLink<IPerkGetter> kye_perk_undead_knowledge => Construct(0x855);
            public static FormLink<IPerkGetter> kye_perk_venomous_knowledge => Construct(0x857);
            public static FormLink<IPerkGetter> kye_perk_elemental_knowledge => Construct(0x859);
            public static FormLink<IPerkGetter> kye_perk_vile_knowledge => Construct(0x85b);
            public static FormLink<IPerkGetter> kye_perk_skeletal_knowledge => Construct(0x85c);
            public static FormLink<IPerkGetter> kye_perk_troll_kin_knowledge => Construct(0x85d);
            public static FormLink<IPerkGetter> kye_perk_weak_willed_knowledge => Construct(0x85e);
            public static FormLink<IPerkGetter> kye_perk_strong_willed_knowledge => Construct(0x85f);
            public static FormLink<IPerkGetter> kye_perk_cave_dwelling_knowledge => Construct(0x860);
            public static FormLink<IPerkGetter> kye_perk_vascular_knowledge => Construct(0x861);
            public static FormLink<IPerkGetter> kye_perk_aquatic_knowledge => Construct(0x862);
            public static FormLink<IPerkGetter> kye_perk_brittle_knowledge => Construct(0x863);
            public static FormLink<IPerkGetter> kye_perk_supernatural_knowledge => Construct(0x864);
            public static FormLink<IPerkGetter> kye_perk_rocky_knowledge => Construct(0x866);
            public static FormLink<IPerkGetter> kye_perk_plant_knowledge => Construct(0x868);
            public static FormLink<IPerkGetter> kye_perk_armors2 => Construct(0x883);
            public static FormLink<IPerkGetter> DummySilverPerk => Construct(0x884);
        }
    }
}
