// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class Perk
        {
            private static FormLink<IPerkGetter> Construct(uint id) => new FormLink<IPerkGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IPerkGetter> kye_perk_undead => Construct(0xaa63);
            public static FormLink<IPerkGetter> kye_perk_plant => Construct(0xaa64);
            public static FormLink<IPerkGetter> kye_perk_skeletal => Construct(0xaa65);
            public static FormLink<IPerkGetter> kye_perk_brittle => Construct(0xaa66);
            public static FormLink<IPerkGetter> kye_perk_dwarven_machine => Construct(0xaa67);
            public static FormLink<IPerkGetter> kye_perk_ghostly => Construct(0x2e171);
            public static FormLink<IPerkGetter> kye_perk_furred => Construct(0x47680);
            public static FormLink<IPerkGetter> kye_perk_supernatural => Construct(0x47681);
            public static FormLink<IPerkGetter> kye_perk_venomous => Construct(0x47682);
            public static FormLink<IPerkGetter> kye_perk_ice_elemental => Construct(0x47683);
            public static FormLink<IPerkGetter> kye_perk_fire_elemental => Construct(0x47684);
            public static FormLink<IPerkGetter> kye_perk_shock_elemental => Construct(0x47685);
            public static FormLink<IPerkGetter> kye_perk_vile => Construct(0x47686);
            public static FormLink<IPerkGetter> kye_perk_troll_kin => Construct(0x47687);
            public static FormLink<IPerkGetter> kye_perk_weak_willed => Construct(0x47688);
            public static FormLink<IPerkGetter> kye_perk_strong_willed => Construct(0x47689);
            public static FormLink<IPerkGetter> kye_perk_cave_dwelling => Construct(0x4768a);
            public static FormLink<IPerkGetter> kye_perk_vascular => Construct(0x4768b);
            public static FormLink<IPerkGetter> kye_perk_aquatic => Construct(0x4768c);
            public static FormLink<IPerkGetter> kye_perk_rocky => Construct(0x4c78e);
            public static FormLink<IPerkGetter> kye_perk_furred_knowledge => Construct(0x6fe9b);
            public static FormLink<IPerkGetter> kye_perk_fat_knowledge => Construct(0x7a09f);
            public static FormLink<IPerkGetter> kye_perk_big_knowledge => Construct(0x7f1a4);
            public static FormLink<IPerkGetter> kye_perk_small_knowledge => Construct(0x842a9);
            public static FormLink<IPerkGetter> kye_perk_armored_knowledge => Construct(0x893ae);
            public static FormLink<IPerkGetter> kye_perk_dwarven_machine_knowledge => Construct(0x8e4b3);
            public static FormLink<IPerkGetter> kye_perk_undead_knowledge => Construct(0x935b8);
            public static FormLink<IPerkGetter> kye_perk_venomous_knowledge => Construct(0x986bc);
            public static FormLink<IPerkGetter> kye_perk_elemental_knowledge => Construct(0x9d7c1);
            public static FormLink<IPerkGetter> kye_perk_vile_knowledge => Construct(0xa28c9);
            public static FormLink<IPerkGetter> kye_perk_skeletal_knowledge => Construct(0xa28ca);
            public static FormLink<IPerkGetter> kye_perk_troll_kin_knowledge => Construct(0xa28cb);
            public static FormLink<IPerkGetter> kye_perk_weak_willed_knowledge => Construct(0xa28cc);
            public static FormLink<IPerkGetter> kye_perk_strong_willed_knowledge => Construct(0xa28cd);
            public static FormLink<IPerkGetter> kye_perk_cave_dwelling_knowledge => Construct(0xa28ce);
            public static FormLink<IPerkGetter> kye_perk_vascular_knowledge => Construct(0xa28cf);
            public static FormLink<IPerkGetter> kye_perk_aquatic_knowledge => Construct(0xa28d0);
            public static FormLink<IPerkGetter> kye_perk_brittle_knowledge => Construct(0xa28d2);
            public static FormLink<IPerkGetter> kye_perk_supernatural_knowledge => Construct(0xa28d4);
            public static FormLink<IPerkGetter> kye_perk_rocky_knowledge => Construct(0xa28d7);
            public static FormLink<IPerkGetter> kye_perk_plant_knowledge => Construct(0xa79da);
            public static FormLink<IPerkGetter> kye_perk_armors2 => Construct(0xb6d0d);
            public static FormLink<IPerkGetter> DummySilverPerk => Construct(0xbbe10);
            public static FormLink<IPerkGetter> kye_perk_fat => Construct(0xaa5e);
            public static FormLink<IPerkGetter> kye_perk_big => Construct(0xaa60);
            public static FormLink<IPerkGetter> kye_perk_small => Construct(0xaa61);
            public static FormLink<IPerkGetter> kye_perk_armored => Construct(0xaa62);
        }
    }
}
