// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class Quest
        {
            private static FormLink<IQuestGetter> Construct(uint id) => new FormLink<IQuestGetter>(ModKey.MakeFormKey(id));
            // public static FormLink<IQuestGetter> kye_armor_quest => Construct(0xb6d0e); If this was for mage armor removed in 9.0.0
            public static FormLink<IQuestGetter> KYE_book_quest => Construct(0x87a);
        }
    }
}
