// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class KnowYourEnemy
    {
        public static class Spell
        {
            private static FormLink<ISpellGetter> Construct(uint id) => new FormLink<ISpellGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ISpellGetter> kye_ab_aquatic => Construct(0xaa37);
            public static FormLink<ISpellGetter> kye_ab_furred => Construct(0xaa38);
            public static FormLink<ISpellGetter> kye_ab_fat => Construct(0xaa3b);
            public static FormLink<ISpellGetter> kye_ab_big => Construct(0xaa3d);
            public static FormLink<ISpellGetter> kye_ab_small => Construct(0xaa3f);
            public static FormLink<ISpellGetter> kye_ab_dwarven_machine => Construct(0xaa41);
            public static FormLink<ISpellGetter> kye_ab_undead => Construct(0xaa43);
            public static FormLink<ISpellGetter> kye_ab_venomous => Construct(0xaa45);
            public static FormLink<ISpellGetter> kye_ab_ice_elemental => Construct(0xaa47);
            public static FormLink<ISpellGetter> kye_ab_fire_elemental => Construct(0xaa49);
            public static FormLink<ISpellGetter> kye_ab_shock_elemental => Construct(0xaa4b);
            public static FormLink<ISpellGetter> kye_ab_plant => Construct(0xaa4d);
            public static FormLink<ISpellGetter> kye_ab_vile => Construct(0xaa4f);
            public static FormLink<ISpellGetter> kye_ab_skeletal => Construct(0xaa51);
            public static FormLink<ISpellGetter> kye_ab_troll_kin => Construct(0xaa53);
            public static FormLink<ISpellGetter> kye_ab_weak_willed => Construct(0xaa55);
            public static FormLink<ISpellGetter> kye_ab_strong_willed => Construct(0xaa56);
            public static FormLink<ISpellGetter> kye_ab_cave_dwelling => Construct(0xaa58);
            public static FormLink<ISpellGetter> kye_ab_vascular => Construct(0xaa5a);
            public static FormLink<ISpellGetter> kye_ab_supernatural => Construct(0xaa5d);
            public static FormLink<ISpellGetter> kye_ab_ghostly => Construct(0x60b93);
            public static FormLink<ISpellGetter> kye_ab_rocky => Construct(0xa28d5);
        }
    }
}
