// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class LightAndShadow
    {
        public static class Keyword
        {
            private static FormLink<IKeywordGetter> Construct(uint id) => new FormLink<IKeywordGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IKeywordGetter> KYEsundamage => Construct(0xaa03);
            public static FormLink<IKeywordGetter> kyesundamagegeneral => Construct(0x23f04);
        }
    }
}
